name: multitask_learning
channels:
  - tensorly
  - conda-forge
  - defaults
dependencies:
  - anyio=2.0.2=py38h50d1736_4
  - appnope=0.1.2=py38h50d1736_1
  - argon2-cffi=20.1.0=py38h5406a74_2
  - astroid=2.4.2=py38_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.3=pyh44b312d_0
  - brotlipy=0.7.0=py38h5406a74_1001
  - ca-certificates=2020.12.5=h033912b_0
  - certifi=2020.12.5=py38h50d1736_1
  - cffi=1.14.4=py38h979bc6b_1
  - chardet=4.0.0=py38h50d1736_1
  - cryptography=3.3.1=py38h6b4ec92_1
  - cycler=0.10.0=py38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=ha233b18_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.4.0=py38h50d1736_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - intel-openmp=2019.4=233
  - ipykernel=5.4.3=py38h9bb44b7_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.6.4=py_0
  - jedi=0.18.0=py38h50d1736_2
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.0=py38h50d1736_1
  - jupyter_server=1.2.2=py38h50d1736_1
  - jupyterlab=3.0.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.1.3=pyhd8ed1ab_0
  - kiwisolver=1.3.0=py38h23ab428_0
  - lazy-object-proxy=1.4.3=py38h1de35cc_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.1.0=hcb84e12_1
  - lz4-c=1.9.2=h79c402e_3
  - markupsafe=1.1.1=py38h5406a74_3
  - matplotlib=3.3.2=hecd8cb5_0
  - matplotlib-base=3.3.2=py38h181983e_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h5406a74_1003
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.2.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h50d1736_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.2.0=py38h50d1736_0
  - numpy=1.19.2=py38h456fd55_0
  - numpy-base=1.19.2=py38hcfb5961_0
  - olefile=0.46=py_0
  - openssl=1.1.1i=h35c211d_0
  - packaging=20.8=pyhd3deb0d_0
  - pandoc=2.11.4=h35c211d_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py38h5270095_0
  - pip=20.2.4=py38hecd8cb5_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.14=pyha770c72_0
  - prompt_toolkit=3.0.14=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.4=pyhd8ed1ab_0
  - pylint=2.6.0=py38_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.17.3=py38h5406a74_2
  - pysocks=1.7.1=py38h50d1736_3
  - python=3.8.5=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.5=pyhd8ed1ab_0
  - pyzmq=20.0.0=py38h23ab428_1
  - readline=8.0=h1de35cc_0
  - requests=2.25.1=pyhd3deb0d_0
  - scipy=1.5.2=py38h2515648_0
  - send2trash=1.5.0=py_0
  - setuptools=50.3.1=py38hecd8cb5_1
  - six=1.15.0=py_0
  - sniffio=1.2.0=py38h50d1736_1
  - sqlite=3.33.0=hffcf06c_0
  - tensorly=0.5.0=py_0
  - terminado=0.9.2=py38h50d1736_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.1=py_0
  - tornado=6.1=py38h9ed2024_0
  - traitlets=5.0.5=py_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - wrapt=1.11.2=py38h1de35cc_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.3=hb1e8313_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
prefix: /opt/miniconda3/envs/multitask_learning
